---
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

services:
  - docker

before_script:
  - php -f tests/init_script.php
  - travis_retry composer self-update --no-interaction --snapshot
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

matrix:
  fast_finish: true
